
import type { Language, PrebuiltVoice } from './types';

export const TEXTS: Record<Language, Record<string, string>> = {
  en: {
    title: "SAMNANG AI TOOLS",
    subtitle: "Your AI-Powered Creative Suite",
    
    // Tool Names
    videoPlanTool: "📝 Video Plan",
    audioTool: "🎤 Audio Generation",
    srtTool: "📜 SRT Generation",
    songwriterTool: "🎵 Music Generation",
    imageTool: "🎨 Image Generation",
    videoTool: "🎬 Video Generation",


    // Input Labels & Placeholders
    inputLabelVideoPlan: "Enter a video topic or idea",
    placeholderVideoPlan: "e.g., A short promotional video for a new coffee shop in Phnom Penh.",
    inputLabelImage: "Describe the image(s) you want to create",
    placeholderImage: "e.g., An astronaut riding a horse on Mars, cinematic lighting.",
    inputLabelVideo: "Describe the video you want to create",
    placeholderVideo: "e.g., A drone shot flying over Angkor Wat at sunrise.",
    inputLabelAudio: "Enter text for each speaker to convert to speech",
    placeholderAudio: "e.g., Hello! This is a voice generated by AI.",
    inputLabelSrt: "Upload an audio file to generate subtitles",
    inputLabelSongwriter: "Song Description",
    
    // Image Tool UI
    numberOfImagesLabel: "Number of Images",
    characterUploadLabel: "Upload Character (Optional)",
    characterUploadButton: "Choose an image...",
    characterRemoveButton: "Remove",

    // Audio Tool UI
    addSpeakerButton: "Add Speaker",
    speakerNameLabel: "Speaker Name",
    voiceLabel: "Voice",
    removeSpeakerButton: "Remove",

    // SRT Tool UI
    uploadAudioButton: "Choose an audio file...",
    changeAudioButton: "Change Audio File",
    srtFileTypes: "MP3, WAV, OGG, M4A",

    // Songwriter Tool UI
    randomButton: "Random",
    instrumentalLabel: "Instrumental",
    styleTagsLabel: "Style & Genre Tags",
    styleTagsPlaceholder: "e.g., flamenco, hip hop, dense synth",

    // UI Elements
    aspectRatioLabel: "Aspect Ratio",

    // Buttons
    generateButton: "Generate",
    generatingButton: "Generating...",
    playAudioButton: "Play Audio",
    playingAudioButton: "Playing...",
    generateNarrationButton: "Generate Narration",
    generatingNarrationButton: "Generating Narration...",
    
    // Output Panel
    outputTitle: "Your Result",
    welcomeMessage: "Your AI-generated content will appear here.",
    welcomeDescription: "Select a tool, enter a prompt, and click 'Generate' to begin.",
    audioGeneratedTitle: "Audio Generated",
    audioGeneratedDescription: "Your text has been converted to speech.",
    srtGeneratedTitle: "SRT File Generated",
    srtGeneratedDescription: "Your audio has been transcribed.",
    songwriterGeneratedTitle: "Song Concept Generated",
    songwriterGeneratedDescription: "Here are the lyrics and musical ideas for your song.",

    // Songwriter Specific
    lyricsSection: "Lyrics",
    musicStyleSection: "Musical Style & Ideas",
    narrationSection: "Lyric Narration",
    effectsSection: "Audio Effects",
    reverbLabel: "Reverb",
    echoLabel: "Echo",
    distortionLabel: "Distortion",
    
    // Video Plan Specific
    scriptSection: "Script",
    sceneHeader: "Scene",
    descriptionHeader: "Visual Description",
    voHeader: "Voiceover (VO)",
    shotListSection: "Shot List",
    aiPromptsSection: "AI Video Generator Prompts",

    // Common
    copyButton: "Copy",
    copiedButton: "Copied!",
    downloadButton: "Download",
    error: "An error occurred. Please try again.",
    generatingVideoMessage: "Generating video... This may take a few minutes.",
    generatingSrtMessage: "Transcribing audio... This may take a moment.",
    
    // API Key Modal
    apiKeyModalTitle: "Paid API Key Required",
    apiKeyModalDescription: "Video generation uses advanced models and requires a paid API key from a Google Cloud project with billing enabled. Please select your key to continue.",
    apiKeyModalDescriptionLink: "Learn more about billing.",
    apiKeyModalButton: "Select API Key",
    apiKeyError: "API key is invalid or missing permissions. Please select a valid key from a paid project and try again.",

    footer: "Powered by Gemini"
  },
  km: {
    title: "SAMNANG AI TOOLS",
    subtitle: "កញ្ចប់ឧបករណ៍ច្នៃប្រឌិត AI របស់អ្នក",
    
    // Tool Names
    videoPlanTool: "📝 ផែនការវីដេអូ",
    audioTool: "🎤 បង្កើតសំឡេង",
    srtTool: "📜 បង្កើត SRT",
    songwriterTool: "🎵 បង្កើតតន្ត្រី",
    imageTool: "🎨 បង្កើតរូបភាព",
    videoTool: "🎬 បង្កើតវីដេអូ",
    
    // Input Labels & Placeholders
    inputLabelVideoPlan: "បញ្ចូលប្រធានបទ ឬគំនិតសម្រាប់វីដេអូ",
    placeholderVideoPlan: "ឧទាហរណ៍៖ វីដេអូផ្សព្វផ្សាយខ្លីសម្រាប់ហាងកាហ្វេថ្មីនៅភ្នំពេញ។",
    inputLabelImage: "ពិពណ៌នារូបភាពដែលអ្នកចង់បង្កើត",
    placeholderImage: "ឧទាហរណ៍៖ អវកាសយានិកជិះសេះនៅលើភពព្រះអង្គារ, ពន្លឺដូចក្នុងរឿងកុន។",
    inputLabelVideo: "ពិពណ៌នាវីដេអូដែលអ្នកចង់បង្កើត",
    placeholderVideo: "ឧទាហរណ៍៖ វីដេអូថតដោយដ្រូនហោះពីលើប្រាសាទអង្គរវត្តពេលព្រះអាទិត្យរះ។",
    inputLabelAudio: "បញ្ចូលអត្ថបទសម្រាប់តួអង្គនីមួយៗដើម្បីបំប្លែងជាសំឡេង",
    placeholderAudio: "ឧទាហរណ៍៖ សួស្តី! នេះគឺជាសំឡេងដែលបង្កើតដោយ AI។",
    inputLabelSrt: "បញ្ចូលឯកសារសំឡេងដើម្បីបង្កើតចំណងជើងរង",
    inputLabelSongwriter: "ការពិពណ៌នាបទចម្រៀង",

    // Image Tool UI
    numberOfImagesLabel: "ចំនួនរូបភាព",
    characterUploadLabel: "បញ្ចូលរូបតួអង្គ (ស្រេចចិត្ត)",
    characterUploadButton: "ជ្រើសរើសរូបភាព...",
    characterRemoveButton: "ដកចេញ",

    // Audio Tool UI
    addSpeakerButton: "បន្ថែមតួអង្គ",
    speakerNameLabel: "ឈ្មោះតួអង្គ",
    voiceLabel: "សំឡេង",
    removeSpeakerButton: "ដកចេញ",
    
    // SRT Tool UI
    uploadAudioButton: "ជ្រើសរើសឯកសារសំឡេង...",
    changeAudioButton: "ប្តូរឯកសារសំឡេង",
    srtFileTypes: "MP3, WAV, OGG, M4A",
    
    // Songwriter Tool UI
    randomButton: "ចៃដន្យ",
    instrumentalLabel: "ឧបករណ៍សុទ្ធ",
    styleTagsLabel: "ស្លាកសញ្ញាស្តាយ & ប្រភេទ",
    styleTagsPlaceholder: "ឧ., ហ្វ្លាម៉ិនកូ, ហ៊ីបហប, សំឡេងសន្ធិស័រដិត",

    // UI Elements
    aspectRatioLabel: "ទំហំ",

    // Buttons
    generateButton: "បង្កើត",
    generatingButton: "កំពុងបង្កើត...",
    playAudioButton: "ចាក់សំឡេង",
    playingAudioButton: "កំពុងចាក់...",
    generateNarrationButton: "បង្កើតសំឡេងអាន",
    generatingNarrationButton: "កំពុងបង្កើតសំឡេងអាន...",

    // Output Panel
    outputTitle: "លទ្ធផលរបស់អ្នក",
    welcomeMessage: "មាតិកាដែលបង្កើតដោយ AI នឹងបង្ហាញនៅទីនេះ។",
    welcomeDescription: "សូមជ្រើសរើសឧបករណ៍ បញ្ចូលប្រយោគបញ្ជា ហើយចុច 'បង្កើត' ដើម្បីចាប់ផ្តើម។",
    audioGeneratedTitle: "បានបង្កើតសំឡេងរួចរាល់",
    audioGeneratedDescription: "អត្ថបទរបស់អ្នកត្រូវបានបំប្លែងជាសំឡេង។",
    srtGeneratedTitle: "បានបង្កើតឯកសារ SRT រួចរាល់",
    srtGeneratedDescription: "សំឡេងរបស់អ្នកត្រូវបានដកស្រង់ជាអក្សរ។",
    songwriterGeneratedTitle: "បានបង្កើតគំនិតបទចម្រៀង",
    songwriterGeneratedDescription: "នេះគឺជាទំនុកច្រៀង និងគំនិតតន្ត្រីសម្រាប់បទចម្រៀងរបស់អ្នក។",

    // Songwriter Specific
    lyricsSection: "ទំនុកច្រៀង",
    musicStyleSection: "ស្ទីល និងគំនិតតន្ត្រី",
    narrationSection: "សំឡេងអានទំនុកច្រៀង",
    effectsSection: "បែបផែនសំឡេង",
    reverbLabel: "សម្លេងរងំ",
    echoLabel: "សម្លេងបន្ទរ",
    distortionLabel: "សម្លេងបែក",

    // Video Plan Specific
    scriptSection: "ស្គ្រីប",
    sceneHeader: "ឈុត",
    descriptionHeader: "ការពិពណ៌នារូបភាព",
    voHeader: "សំឡេងអត្ថាធិប្បាយ (VO)",
    shotListSection: "បញ្ជីនៃការថត",
    aiPromptsSection: "ប្រយោគបញ្ជាសម្រាប់ AI បង្កើតវីដេអូ",

    // Common
    copyButton: "ចម្លង",
    copiedButton: "បានចម្លង!",
    downloadButton: "ទាញយក",
    error: "មានបញ្ហា។ សូមព្យាយាមម្តងទៀត។",
    generatingVideoMessage: "កំពុងបង្កើតវីដេអូ... ការងារនេះអាចចំណាយពេលច្រើននាទី។",
    generatingSrtMessage: "កំពុងដកស្រង់សំឡេង... ការងារនេះអាចចំណាយពេលបន្តិច។",

    // API Key Modal
    apiKeyModalTitle: "ត្រូវការ API Key បង់ប្រាក់",
    apiKeyModalDescription: "ការបង្កើតវីដេអូប្រើប្រាស់ម៉ូដែលកម្រិតខ្ពស់ និងទាមទារ API key ដែលបានបង់ប្រាក់ពីគម្រោង Google Cloud ដែលបានเปิดใช้งาน billing។ សូមជ្រើសរើស key របស់អ្នកដើម្បីបន្ត។",
    apiKeyModalDescriptionLink: "ស្វែងយល់បន្ថែមអំពីការបង់ប្រាក់។",
    apiKeyModalButton: "ជ្រើសរើស API Key",
    apiKeyError: "API key មិនត្រឹមត្រូវ ឬគ្មានសិទ្ធិគ្រប់គ្រាន់។ សូមជ្រើសរើស key ដែលត្រឹមត្រូវពីគម្រោងបង់ប្រាក់ រួចព្យាយាមម្តងទៀត។",

    footer: "ដំណើរការដោយ Gemini"
  }
};

export const VOICE_DESCRIPTIONS: Record<PrebuiltVoice, string> = {
    Kore: "Male, Calm & Clear",
    Puck: "Male, Energetic & Youthful",
    Charon: "Male, Deep & Authoritative",
    Fenrir: "Female, Warm & Friendly",
    Zephyr: "Female, Bright & Cheerful"
};
