
import React from 'react';
import type { Language, VideoPlan, Tool, SongLyrics } from '../types';
import { TEXTS } from '../constants';
import { LoadingSpinner } from './LoadingSpinner';
import { VideoProductionOutput } from './VideoProductionOutput';
import { AudioResult } from './AudioResult';
import { SrtResult } from './SrtResult';
import { SongwriterResult } from './SongwriterResult';

interface OutputPanelProps {
  language: Language;
  activeTool: Tool;
  isLoading: boolean;
  loadingMessage: string;
  result: VideoPlan | string | string[] | SongLyrics | null;
  error: string | null;
  onGenerateNarration: (lyrics: string) => void;
  isNarrationLoading: boolean;
  narrationAudio: string | null;
}

const WelcomeState: React.FC<{ language: Language }> = ({ language }) => (
  <div className="text-center p-8 flex flex-col justify-center items-center h-full">
    <svg className="mx-auto h-16 w-16 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c.242.013.487.02.73.022h.014c.243-.002.487-.009.73-.022M9.75 3.104C11.39 3.18 13 4.484 13 6.125v2.531M15 14.5v-1.345a2.25 2.25 0 01.659-1.591l4.091-4.091a2.25 2.25 0 013.182 3.182l-4.091 4.091a2.25 2.25 0 01-1.591.659V14.5m-5.25 0h5.25m-5.25 0a2.25 2.25 0 01-2.25-2.25V6.125c0-1.641 1.61-2.945 3.25-2.844" />
    </svg>
    <h3 className="mt-4 text-xl font-medium text-white">{TEXTS[language].welcomeMessage}</h3>
    <p className="mt-1 text-gray-400 max-w-sm">{TEXTS[language].welcomeDescription}</p>
  </div>
);

const ErrorState: React.FC<{ message: string }> = ({ message }) => (
    <div className="text-center p-8 bg-red-900/20 border border-red-500/50 rounded-lg flex flex-col justify-center items-center h-full">
        <svg className="mx-auto h-12 w-12 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h3 className="mt-4 text-xl font-medium text-red-200">Error</h3>
        <p className="mt-1 text-red-300">{message}</p>
  </div>
);

const ResultDisplay: React.FC<{ 
    language: Language; 
    activeTool: Tool; 
    result: VideoPlan | string | string[] | SongLyrics;
    onGenerateNarration: (lyrics: string) => void;
    isNarrationLoading: boolean;
    narrationAudio: string | null;
}> = ({ language, activeTool, result, onGenerateNarration, isNarrationLoading, narrationAudio }) => {
    if (activeTool === 'videoPlan' && typeof result === 'object' && 'script' in result) {
        return <VideoProductionOutput language={language} plan={result as VideoPlan} />;
    }
    
    if (activeTool === 'image' && Array.isArray(result)) {
        return (
            <div className="grid grid-cols-2 gap-4">
                {result.map((base64, index) => {
                    const imageUrl = `data:image/png;base64,${base64}`;
                    return (
                        <div key={index} className="space-y-2 group relative">
                            <img src={imageUrl} alt={`Generated by AI ${index + 1}`} className="rounded-lg shadow-lg w-full h-full object-cover" />
                             <a href={imageUrl} download={`samnang-ai-image-${index + 1}.png`} className="absolute bottom-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity bg-indigo-600/80 text-white p-2 rounded-full">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
                                </svg>
                            </a>
                        </div>
                    );
                })}
            </div>
        );
    }
    
    if (activeTool === 'video' && typeof result === 'string') {
        const videoUrl = `${result}&key=${process.env.API_KEY}`;
        return (
             <div className="space-y-4">
                <video controls src={videoUrl} className="rounded-lg shadow-lg mx-auto w-full"></video>
                <a href={videoUrl} target="_blank" rel="noopener noreferrer" className="w-full block text-center py-2 px-4 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-md transition-colors duration-200">
                    {TEXTS[language].downloadButton}
                </a>
             </div>
        )
    }

    if (activeTool === 'audio' && typeof result === 'string') {
        return <AudioResult language={language} base64Audio={result} />;
    }
    
    if (activeTool === 'srt' && typeof result === 'string') {
        return <SrtResult language={language} srtContent={result} />;
    }

    if (activeTool === 'songwriter' && typeof result === 'object' && 'lyrics' in result) {
        return <SongwriterResult 
                    language={language} 
                    song={result as SongLyrics} 
                    onGenerateNarration={onGenerateNarration}
                    isNarrationLoading={isNarrationLoading}
                    narrationAudio={narrationAudio}
                />;
    }

    return null;
}

export const OutputPanel: React.FC<OutputPanelProps> = ({ language, activeTool, isLoading, loadingMessage, result, error, onGenerateNarration, isNarrationLoading, narrationAudio }) => {
  return (
    <div className="bg-gray-800 p-6 rounded-lg shadow-lg min-h-[70vh] flex flex-col">
      <div className="flex-grow overflow-y-auto">
        {isLoading && <LoadingSpinner message={loadingMessage} />}
        {error && <ErrorState message={error} />}
        {!isLoading && !error && !result && <WelcomeState language={language} />}
        {!isLoading && !error && result && 
            <ResultDisplay 
                language={language} 
                activeTool={activeTool} 
                result={result} 
                onGenerateNarration={onGenerateNarration}
                isNarrationLoading={isNarrationLoading}
                narrationAudio={narrationAudio}
            />}
      </div>
    </div>
  );
};
